### ISSUE TITLE
bug: card real pointer div classname

### ISSUE THREAD

**Issue by Vicentesan** [guhrodrrigues/luxe#20]
Hey there, i was trying to add the card real pointer into my new next 15 project and this error was triggered in the IDE:

```
Type '{ className: string; style: { background: MotionValue<string>; }; }' is not assignable to type 'IntrinsicAttributes & HTMLAttributesWithoutMotionProps<unknown, unknown> & MotionProps & RefAttributes<unknown>'.
  Property 'className' does not exist on type 'IntrinsicAttributes & HTMLAttributesWithoutMotionProps<unknown, unknown> & MotionProps & RefAttributes<unknown>'.ts(2322)
  ```
  
  Idk what it can be, and how it fix it so im reporting here instead of doing a PR...

**Comment by Vicentesan** [comment]
If you guys need any more details, just tell me

**Comment by guhrodrrigues** [comment]
Hey man, can you tell me if this new commit has solved the problem?

**Comment by Vicentesan** [comment]
No mate... same error: 

```
type '{ className: string; style: { background: MotionValue<string>; }; }' is not assignable to type 'IntrinsicAttributes & HTMLAttributesWithoutMotionProps<unknown, unknown> & MotionProps & RefAttributes<unknown>'.
  Property 'className' does not exist on type 'IntrinsicAttributes & HTMLAttributesWithoutMotionProps<unknown, unknown> & MotionProps & RefAttributes<unknown>'.ts(2322)```

**Comment by guhrodrrigues** [comment]
Dude, everything is normal with the Card Revealed Pointer component. Can you give me more details?

**Comment by Vicentesan** [comment]
Now that Im reading it more deep it seems to be a framer issue, not yours

**Comment by guhrodrrigues** [comment]
Hey @Vicentesan, did it work for you?

**Comment by Vicentesan** [comment]
yeah, its working fine, but it still have the error in the IDE, i think its a framer-motion issue... i will report to them
